# Generated by Django 6.0.3 on 2026-04-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_course_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="last_notification_sent",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата последней отправки уведомления об обновлении"
            ),
        ),
    ]
